// <auto-generated />
using CombatCatalyst.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CombatCatalyst.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("CombatCatalyst.Server.Models.LegendaryAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "desc");

                    b.Property<int>("MonsterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.HasKey("Id");

                    b.HasIndex("MonsterId");

                    b.ToTable("LegendaryActions");

                    b.HasAnnotation("Relational:JsonPropertyName", "legendary_actions");
                });

            modelBuilder.Entity("CombatCatalyst.Server.Models.Monster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alignment")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "alignment");

                    b.Property<int>("ArmorClass")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "armor_class");

                    b.Property<string>("ChallengeRating")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "challenge_rating");

                    b.Property<int>("Charisma")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "charisma");

                    b.Property<int>("Constitution")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "constitution");

                    b.Property<int>("Dexterity")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "dexterity");

                    b.Property<string>("HitDice")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "hit_dice");

                    b.Property<int>("HitPoints")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "hit_points");

                    b.Property<int>("Intelligence")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "intelligence");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "size");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "slug");

                    b.Property<int>("Strength")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "strength");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "type");

                    b.Property<int>("Wisdom")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "wisdom");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Monsters");
                });

            modelBuilder.Entity("CombatCatalyst.Server.Models.MonsterAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "desc");

                    b.Property<int>("MonsterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.HasKey("Id");

                    b.HasIndex("MonsterId");

                    b.ToTable("MonsterActions");

                    b.HasAnnotation("Relational:JsonPropertyName", "actions");
                });

            modelBuilder.Entity("CombatCatalyst.Server.Models.Reaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "desc");

                    b.Property<int>("MonsterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.HasKey("Id");

                    b.HasIndex("MonsterId");

                    b.ToTable("Reactions");

                    b.HasAnnotation("Relational:JsonPropertyName", "reactions");
                });

            modelBuilder.Entity("CombatCatalyst.Server.Models.SpecialAbility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "desc");

                    b.Property<int>("MonsterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.HasKey("Id");

                    b.HasIndex("MonsterId");

                    b.ToTable("SpecialAbilities");

                    b.HasAnnotation("Relational:JsonPropertyName", "special_abilities");
                });

            modelBuilder.Entity("CombatCatalyst.Server.Models.LegendaryAction", b =>
                {
                    b.HasOne("CombatCatalyst.Server.Models.Monster", "Monster")
                        .WithMany("LegendaryActions")
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monster");
                });

            modelBuilder.Entity("CombatCatalyst.Server.Models.MonsterAction", b =>
                {
                    b.HasOne("CombatCatalyst.Server.Models.Monster", "Monster")
                        .WithMany("Actions")
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monster");
                });

            modelBuilder.Entity("CombatCatalyst.Server.Models.Reaction", b =>
                {
                    b.HasOne("CombatCatalyst.Server.Models.Monster", "Monster")
                        .WithMany("Reactions")
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monster");
                });

            modelBuilder.Entity("CombatCatalyst.Server.Models.SpecialAbility", b =>
                {
                    b.HasOne("CombatCatalyst.Server.Models.Monster", "Monster")
                        .WithMany("SpecialAbilities")
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monster");
                });

            modelBuilder.Entity("CombatCatalyst.Server.Models.Monster", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("LegendaryActions");

                    b.Navigation("Reactions");

                    b.Navigation("SpecialAbilities");
                });
#pragma warning restore 612, 618
        }
    }
}
